I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 124, in script
    $ textC = newsText[currNews]
  File "game/scripts/script.rpy", line 124, in <module>
    $ textC = newsText[currNews]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 124, in script
    $ textC = newsText[currNews]
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/script.rpy", line 124, in <module>
    $ textC = newsText[currNews]
  File "C:\renpy-8.0.3-sdk\renpy\revertable.py", line 217, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
DGame 1.0
Wed Nov 16 05:51:55 2022
